
// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	"os"

	"testing"
	"testing/internal/testdeps"



	_test "github.com/agentfabric/api-gateway/internal/models"


)

var tests = []testing.InternalTest{

	{"TestNormalizeDecisionResult", _test.TestNormalizeDecisionResult},

	{"TestDefaultDecisionExplanation_PolicyDeny", _test.TestDefaultDecisionExplanation_PolicyDeny},

	{"TestDefaultDecisionExplanation_Fallback", _test.TestDefaultDecisionExplanation_Fallback},

}

var benchmarks = []testing.InternalBenchmark{

}

var fuzzTargets = []testing.InternalFuzzTarget{

}

var examples = []testing.InternalExample{

}

func init() {

	testdeps.ModulePath = "github.com/agentfabric/api-gateway"
	testdeps.ImportPath = "github.com/agentfabric/api-gateway/internal/models"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	os.Exit(m.Run())

}

