ALTER TABLE pricing_rules
    ADD COLUMN IF NOT EXISTS cache_read_per_million NUMERIC(12,6) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS cache_write_per_million NUMERIC(12,6) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS reasoning_per_million NUMERIC(12,6) NOT NULL DEFAULT 0;

ALTER TABLE spans
    ADD COLUMN IF NOT EXISTS cache_read_tokens BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS cache_write_tokens BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS reasoning_tokens BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS input_cost_usd NUMERIC(12,8) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS output_cost_usd NUMERIC(12,8) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS cache_read_cost_usd NUMERIC(12,8) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS cache_write_cost_usd NUMERIC(12,8) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS reasoning_cost_usd NUMERIC(12,8) NOT NULL DEFAULT 0;
