ALTER TABLE policy_rules
    ADD COLUMN IF NOT EXISTS guardrails JSONB NOT NULL DEFAULT '[]'::jsonb,
    ADD COLUMN IF NOT EXISTS schema_json TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS unsafe_categories JSONB NOT NULL DEFAULT '[]'::jsonb,
    ADD COLUMN IF NOT EXISTS rollout_percent INTEGER NOT NULL DEFAULT 100,
    ADD COLUMN IF NOT EXISTS version INTEGER NOT NULL DEFAULT 1;
