
// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	"os"

	"testing"
	"testing/internal/testdeps"



	_test "github.com/govagn/api-gateway/cmd/server"


)

var tests = []testing.InternalTest{

	{"TestServe_TLSDisabled", _test.TestServe_TLSDisabled},

	{"TestServe_TLSMissingCert", _test.TestServe_TLSMissingCert},

	{"TestServe_TLSCertFileNotFound", _test.TestServe_TLSCertFileNotFound},

	{"TestParseSecrets_MultipleSecrets", _test.TestParseSecrets_MultipleSecrets},

	{"TestParseSecrets_TrimsWhitespace", _test.TestParseSecrets_TrimsWhitespace},

	{"TestParseSecrets_SingleSecret", _test.TestParseSecrets_SingleSecret},

	{"TestParseSecrets_EmptyFallsBackToDefault", _test.TestParseSecrets_EmptyFallsBackToDefault},

	{"TestParseSecrets_SkipsEmptySegments", _test.TestParseSecrets_SkipsEmptySegments},

	{"TestValidateProductionConfig_StrictDisabled", _test.TestValidateProductionConfig_StrictDisabled},

	{"TestValidateProductionConfig_RejectsUnsafeDefaults", _test.TestValidateProductionConfig_RejectsUnsafeDefaults},

	{"TestValidateProductionConfig_AcceptsSafeValues", _test.TestValidateProductionConfig_AcceptsSafeValues},

	{"TestOpenAPISpec_IsWellFormedAndCoversCoreRoutes", _test.TestOpenAPISpec_IsWellFormedAndCoversCoreRoutes},

	{"TestServeSwaggerUI_EmbedsSpecURL", _test.TestServeSwaggerUI_EmbedsSpecURL},

	{"TestServeOpenAPISpec_ServesConfiguredFile", _test.TestServeOpenAPISpec_ServesConfiguredFile},

}

var benchmarks = []testing.InternalBenchmark{

}

var fuzzTargets = []testing.InternalFuzzTarget{

}

var examples = []testing.InternalExample{

}

func init() {

	testdeps.ModulePath = "github.com/govagn/api-gateway"
	testdeps.ImportPath = "github.com/govagn/api-gateway/cmd/server"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	os.Exit(m.Run())

}

