
// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	"os"

	"testing"
	"testing/internal/testdeps"



	_test "github.com/govagn/api-gateway/internal/netproxy"


)

var tests = []testing.InternalTest{

	{"TestCA_NewCA_GeneratesCert", _test.TestCA_NewCA_GeneratesCert},

	{"TestCA_TLSConfigFor_CachesLeaf", _test.TestCA_TLSConfigFor_CachesLeaf},

	{"TestCA_TLSConfigFor_DifferentHostnames", _test.TestCA_TLSConfigFor_DifferentHostnames},

	{"TestCA_LeafSignedByCA", _test.TestCA_LeafSignedByCA},

	{"TestKnownLLMHosts_OpenAI", _test.TestKnownLLMHosts_OpenAI},

	{"TestKnownLLMHosts_Anthropic", _test.TestKnownLLMHosts_Anthropic},

	{"TestStripPort", _test.TestStripPort},

	{"TestExtractKey_Bearer", _test.TestExtractKey_Bearer},

	{"TestExtractKey_XApiKey", _test.TestExtractKey_XApiKey},

	{"TestExtractKey_Missing", _test.TestExtractKey_Missing},

	{"TestExtractKey_BearerCaseInsensitive", _test.TestExtractKey_BearerCaseInsensitive},

	{"TestExtractKey_RejectsConflictingHeaders", _test.TestExtractKey_RejectsConflictingHeaders},

	{"TestRemoveHopByHopHeaders", _test.TestRemoveHopByHopHeaders},

	{"TestServeHTTP_NonConnectRejected", _test.TestServeHTTP_NonConnectRejected},

	{"TestHandleIntercepted_RawKey_Forwarded_SpanRecorded", _test.TestHandleIntercepted_RawKey_Forwarded_SpanRecorded},

	{"TestHandleIntercepted_NoKey_ForwardedWithoutSpan", _test.TestHandleIntercepted_NoKey_ForwardedWithoutSpan},

	{"TestHandleIntercepted_VirtualKeyPrefix_NilPool_Returns401", _test.TestHandleIntercepted_VirtualKeyPrefix_NilPool_Returns401},

	{"TestHandleIntercepted_UnknownProvider_ForwardsRaw", _test.TestHandleIntercepted_UnknownProvider_ForwardsRaw},

	{"TestPassthrough_NonLLMHost_DataCopied", _test.TestPassthrough_NonLLMHost_DataCopied},

	{"TestMITMConnect_TLSHandshake_SpanRecorded", _test.TestMITMConnect_TLSHandshake_SpanRecorded},

}

var benchmarks = []testing.InternalBenchmark{

}

var fuzzTargets = []testing.InternalFuzzTarget{

}

var examples = []testing.InternalExample{

}

func init() {

	testdeps.ModulePath = "github.com/govagn/api-gateway"
	testdeps.ImportPath = "github.com/govagn/api-gateway/internal/netproxy"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	os.Exit(m.Run())

}

