
// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	"os"

	"testing"
	"testing/internal/testdeps"



	_test "github.com/agentfabric/api-gateway/internal/prompts"


)

var tests = []testing.InternalTest{

	{"TestNormalizeEnvironment", _test.TestNormalizeEnvironment},

	{"TestAttachCurrentReleases", _test.TestAttachCurrentReleases},

	{"TestReleaseKey", _test.TestReleaseKey},

	{"TestListCatalogAttachesCurrentRelease", _test.TestListCatalogAttachesCurrentRelease},

	{"TestUpsertVersionValidatesAndNormalizesFields", _test.TestUpsertVersionValidatesAndNormalizesFields},

	{"TestPromoteBuildsReleaseFromSelectedVersion", _test.TestPromoteBuildsReleaseFromSelectedVersion},

	{"TestListCatalogReturnsVersionError", _test.TestListCatalogReturnsVersionError},

	{"TestUpsertVersionRequiresPromptAndContent", _test.TestUpsertVersionRequiresPromptAndContent},

	{"TestPromoteValidatesInputs", _test.TestPromoteValidatesInputs},

}

var benchmarks = []testing.InternalBenchmark{

}

var fuzzTargets = []testing.InternalFuzzTarget{

}

var examples = []testing.InternalExample{

}

func init() {

	testdeps.ModulePath = "github.com/agentfabric/api-gateway"
	testdeps.ImportPath = "github.com/agentfabric/api-gateway/internal/prompts"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	os.Exit(m.Run())

}

