
// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	"os"

	"testing"
	"testing/internal/testdeps"



	_test "github.com/agentfabric/collector/internal/exporter"


)

var tests = []testing.InternalTest{

	{"TestExport_Success", _test.TestExport_Success},

	{"TestExport_ServerError_Returns5xx", _test.TestExport_ServerError_Returns5xx},

	{"TestExport_ContextCancelled", _test.TestExport_ContextCancelled},

	{"TestExport_InvalidEndpoint", _test.TestExport_InvalidEndpoint},

	{"TestExport_SetsRequiredHeaders", _test.TestExport_SetsRequiredHeaders},

	{"TestExport_EmptySpans_StillSendsRequest", _test.TestExport_EmptySpans_StillSendsRequest},

}

var benchmarks = []testing.InternalBenchmark{

}

var fuzzTargets = []testing.InternalFuzzTarget{

}

var examples = []testing.InternalExample{

}

func init() {

	testdeps.ModulePath = "github.com/agentfabric/collector"
	testdeps.ImportPath = "github.com/agentfabric/collector/internal/exporter"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	os.Exit(m.Run())

}

