
// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	"os"

	"testing"
	"testing/internal/testdeps"



	_test "github.com/govagn/api-gateway/internal/budget"


)

var tests = []testing.InternalTest{

	{"TestBudgetEnforcer_Unlimited", _test.TestBudgetEnforcer_Unlimited},

	{"TestBudgetEnforcer_UnderLimit", _test.TestBudgetEnforcer_UnderLimit},

	{"TestBudgetEnforcer_OverTokenLimit", _test.TestBudgetEnforcer_OverTokenLimit},

	{"TestBudgetEnforcer_OverCostLimit", _test.TestBudgetEnforcer_OverCostLimit},

	{"TestBudgetEnforcer_SoftLimitOnly", _test.TestBudgetEnforcer_SoftLimitOnly},

	{"TestBudgetEnforcer_AlertThreshold", _test.TestBudgetEnforcer_AlertThreshold},

	{"TestBudgetEnforcer_NoBudget", _test.TestBudgetEnforcer_NoBudget},

	{"TestCurrentPeriodStart", _test.TestCurrentPeriodStart},

}

var benchmarks = []testing.InternalBenchmark{

}

var fuzzTargets = []testing.InternalFuzzTarget{

}

var examples = []testing.InternalExample{

}

func init() {

	testdeps.ModulePath = "github.com/govagn/api-gateway"
	testdeps.ImportPath = "github.com/govagn/api-gateway/internal/budget"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	os.Exit(m.Run())

}

