
// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	"os"

	"testing"
	"testing/internal/testdeps"



	_test "github.com/agentfabric/collector/internal/processor"


)

var tests = []testing.InternalTest{

	{"TestComputeCost_ClaudeHaiku", _test.TestComputeCost_ClaudeHaiku},

	{"TestComputeCost_GPT4o", _test.TestComputeCost_GPT4o},

	{"TestComputeCost_GPT4oMini", _test.TestComputeCost_GPT4oMini},

	{"TestComputeCost_ClaudeSonnet", _test.TestComputeCost_ClaudeSonnet},

	{"TestComputeCost_PartialTokens", _test.TestComputeCost_PartialTokens},

	{"TestComputeCost_ZeroTokens", _test.TestComputeCost_ZeroTokens},

	{"TestComputeCost_UnknownModel", _test.TestComputeCost_UnknownModel},

	{"TestComputeCost_CaseInsensitive", _test.TestComputeCost_CaseInsensitive},

	{"TestComputeCost_InputOutputAreIndependent", _test.TestComputeCost_InputOutputAreIndependent},

	{"TestComputeCost_UsesConfiguredPricing", _test.TestComputeCost_UsesConfiguredPricing},

	{"TestDetectFramework_CrewAIByAttribute", _test.TestDetectFramework_CrewAIByAttribute},

	{"TestDetectFramework_CrewAIByCrewID", _test.TestDetectFramework_CrewAIByCrewID},

	{"TestDetectFramework_LangGraphByAttribute", _test.TestDetectFramework_LangGraphByAttribute},

	{"TestDetectFramework_GoogleADK", _test.TestDetectFramework_GoogleADK},

	{"TestDetectFramework_OpenAIByRunID", _test.TestDetectFramework_OpenAIByRunID},

	{"TestDetectFramework_AnthropicByModel", _test.TestDetectFramework_AnthropicByModel},

	{"TestDetectFramework_ModelFallbackClaude", _test.TestDetectFramework_ModelFallbackClaude},

	{"TestDetectFramework_ModelFallbackGPT", _test.TestDetectFramework_ModelFallbackGPT},

	{"TestDetectFramework_ModelFallbackGemini", _test.TestDetectFramework_ModelFallbackGemini},

	{"TestDetectFramework_SpanNameFallbackCrewAI", _test.TestDetectFramework_SpanNameFallbackCrewAI},

	{"TestDetectFramework_SpanNameFallbackLangGraph", _test.TestDetectFramework_SpanNameFallbackLangGraph},

	{"TestDetectFramework_Unknown", _test.TestDetectFramework_Unknown},

	{"TestDetectFramework_ServerSide_NeverTrustsClientFrameworkAttr", _test.TestDetectFramework_ServerSide_NeverTrustsClientFrameworkAttr},

	{"TestScrubPII_SSN", _test.TestScrubPII_SSN},

	{"TestScrubPII_CreditCard", _test.TestScrubPII_CreditCard},

	{"TestScrubPII_Email", _test.TestScrubPII_Email},

	{"TestScrubPII_Credentials", _test.TestScrubPII_Credentials},

	{"TestScrubPII_Password", _test.TestScrubPII_Password},

	{"TestScrubPII_UKPostcode", _test.TestScrubPII_UKPostcode},

	{"TestScrubPII_UKPhone", _test.TestScrubPII_UKPhone},

	{"TestScrubPII_Name", _test.TestScrubPII_Name},

	{"TestScrubPII_CleanDataUnchanged", _test.TestScrubPII_CleanDataUnchanged},

	{"TestScrubPII_AllSevenPatterns", _test.TestScrubPII_AllSevenPatterns},

	{"TestScrubPII_EmptyAttrs", _test.TestScrubPII_EmptyAttrs},

}

var benchmarks = []testing.InternalBenchmark{

}

var fuzzTargets = []testing.InternalFuzzTarget{

}

var examples = []testing.InternalExample{

}

func init() {

	testdeps.ModulePath = "github.com/agentfabric/collector"
	testdeps.ImportPath = "github.com/agentfabric/collector/internal/processor"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	os.Exit(m.Run())

}

