
// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	"os"

	"testing"
	"testing/internal/testdeps"



	_test "github.com/govagn/api-gateway/internal/recommendations"


)

var tests = []testing.InternalTest{

	{"TestListRecommendations_GeneratesActionableRecommendations", _test.TestListRecommendations_GeneratesActionableRecommendations},

	{"TestUpdateStatus_RejectsUnknownStatuses", _test.TestUpdateStatus_RejectsUnknownStatuses},

}

var benchmarks = []testing.InternalBenchmark{

}

var fuzzTargets = []testing.InternalFuzzTarget{

}

var examples = []testing.InternalExample{

}

func init() {

	testdeps.ModulePath = "github.com/govagn/api-gateway"
	testdeps.ImportPath = "github.com/govagn/api-gateway/internal/recommendations"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	os.Exit(m.Run())

}

