
// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	"os"

	"testing"
	"testing/internal/testdeps"



	_test "github.com/govagn/api-gateway/internal/handlers"


)

var tests = []testing.InternalTest{

	{"TestAuditEntriesToPolicyEvents_CorrelatesSpanMetadata", _test.TestAuditEntriesToPolicyEvents_CorrelatesSpanMetadata},

	{"TestPreviewPolicyDecision_MapsDecisionFields", _test.TestPreviewPolicyDecision_MapsDecisionFields},

	{"TestBuildTrace_EmptySpans", _test.TestBuildTrace_EmptySpans},

	{"TestBuildTrace_SingleSpan", _test.TestBuildTrace_SingleSpan},

	{"TestBuildTrace_AggregatesCost", _test.TestBuildTrace_AggregatesCost},

	{"TestBuildTrace_AggregatesToknes", _test.TestBuildTrace_AggregatesToknes},

	{"TestBuildTrace_ErrorCountAndStatus", _test.TestBuildTrace_ErrorCountAndStatus},

	{"TestBuildTrace_DerivesInsights", _test.TestBuildTrace_DerivesInsights},

	{"TestBuildTrace_Duration", _test.TestBuildTrace_Duration},

	{"TestBuildTrace_StartTime", _test.TestBuildTrace_StartTime},

	{"TestBuildTopologyGraph_EmptySpans", _test.TestBuildTopologyGraph_EmptySpans},

	{"TestBuildTopologyGraph_SingleSpan", _test.TestBuildTopologyGraph_SingleSpan},

	{"TestBuildTopologyGraph_LinearChain", _test.TestBuildTopologyGraph_LinearChain},

	{"TestBuildTopologyGraph_DeduplicatesNodes", _test.TestBuildTopologyGraph_DeduplicatesNodes},

	{"TestBuildTopologyGraph_CallCountAccumulates", _test.TestBuildTopologyGraph_CallCountAccumulates},

	{"TestBuildTopologyGraph_P02Fix_BatchNotLoop", _test.TestBuildTopologyGraph_P02Fix_BatchNotLoop},

	{"TestWriteError_HelperExistsAndProducesJSON", _test.TestWriteError_HelperExistsAndProducesJSON},

	{"TestParseIntOr_DefaultOnEmpty", _test.TestParseIntOr_DefaultOnEmpty},

	{"TestParseCostReportQuery_ReadsDimensionFilters", _test.TestParseCostReportQuery_ReadsDimensionFilters},

	{"TestParseIntOr_ParsesValidInt", _test.TestParseIntOr_ParsesValidInt},

	{"TestParseIntOr_DefaultOnInvalid", _test.TestParseIntOr_DefaultOnInvalid},

}

var benchmarks = []testing.InternalBenchmark{

}

var fuzzTargets = []testing.InternalFuzzTarget{

}

var examples = []testing.InternalExample{

}

func init() {

	testdeps.ModulePath = "github.com/govagn/api-gateway"
	testdeps.ImportPath = "github.com/govagn/api-gateway/internal/handlers"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	os.Exit(m.Run())

}

