
// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	"os"

	"testing"
	"testing/internal/testdeps"



	_test "github.com/govagn/collector/internal/config"


)

var tests = []testing.InternalTest{

	{"TestLoad_StrictProductionRequiresJWTSecret", _test.TestLoad_StrictProductionRequiresJWTSecret},

	{"TestLoad_StrictProductionAcceptsJWTSecret", _test.TestLoad_StrictProductionAcceptsJWTSecret},

	{"TestLoad_StrictProductionRequiresGatewayAuthToken", _test.TestLoad_StrictProductionRequiresGatewayAuthToken},

	{"TestLoad_StrictProductionRequiresTLSFilesWhenEnabled", _test.TestLoad_StrictProductionRequiresTLSFilesWhenEnabled},

	{"TestLoad_StrictProductionRejectsAuthDisabled", _test.TestLoad_StrictProductionRejectsAuthDisabled},

	{"TestLoad_StrictProductionRejectsDefaultGatewayEndpoint", _test.TestLoad_StrictProductionRejectsDefaultGatewayEndpoint},

	{"TestLoad_StrictProductionRejectsDevelopmentJWTSecretAlias", _test.TestLoad_StrictProductionRejectsDevelopmentJWTSecretAlias},

	{"TestLoad_Defaults", _test.TestLoad_Defaults},

	{"TestLoad_EnvOverrides", _test.TestLoad_EnvOverrides},

	{"TestLoad_Idempotent", _test.TestLoad_Idempotent},

	{"TestLoad_NodeNameFallback", _test.TestLoad_NodeNameFallback},

}

var benchmarks = []testing.InternalBenchmark{

}

var fuzzTargets = []testing.InternalFuzzTarget{

}

var examples = []testing.InternalExample{

}

func init() {

	testdeps.ModulePath = "github.com/govagn/collector"
	testdeps.ImportPath = "github.com/govagn/collector/internal/config"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	os.Exit(m.Run())

}

