
// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	"os"

	"testing"
	"testing/internal/testdeps"



	_test "github.com/agentfabric/api-gateway/internal/store"


)

var tests = []testing.InternalTest{

	{"TestBuildCostSpikeReport_RanksPositiveDeltas", _test.TestBuildCostSpikeReport_RanksPositiveDeltas},

	{"TestBuildContributorGroups_AggregatesByDimension", _test.TestBuildContributorGroups_AggregatesByDimension},

	{"TestExplainCostSpike_HandlesNewSpend", _test.TestExplainCostSpike_HandlesNewSpend},

	{"TestNormalizeCostReportQuery_DefaultsAndCap", _test.TestNormalizeCostReportQuery_DefaultsAndCap},

}

var benchmarks = []testing.InternalBenchmark{

}

var fuzzTargets = []testing.InternalFuzzTarget{

}

var examples = []testing.InternalExample{

}

func init() {

	testdeps.ModulePath = "github.com/agentfabric/api-gateway"
	testdeps.ImportPath = "github.com/agentfabric/api-gateway/internal/store"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	os.Exit(m.Run())

}

