
// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	"os"

	"testing"
	"testing/internal/testdeps"



	_test "github.com/govagn/collector/cmd/collector"


)

var tests = []testing.InternalTest{

	{"TestNewHTTPServer_HardenedTimeouts", _test.TestNewHTTPServer_HardenedTimeouts},

	{"TestCollectorReady_DoesNotFollowGatewayRedirects", _test.TestCollectorReady_DoesNotFollowGatewayRedirects},

}

var benchmarks = []testing.InternalBenchmark{

}

var fuzzTargets = []testing.InternalFuzzTarget{

}

var examples = []testing.InternalExample{

}

func init() {

	testdeps.ModulePath = "github.com/govagn/collector"
	testdeps.ImportPath = "github.com/govagn/collector/cmd/collector"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	os.Exit(m.Run())

}

