
// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	"os"

	"testing"
	"testing/internal/testdeps"



	_test "github.com/agentfabric/api-gateway/internal/proxy"


)

var tests = []testing.InternalTest{

	{"TestPricingPrecedence_DBOverridesEnvConfig", _test.TestPricingPrecedence_DBOverridesEnvConfig},

	{"TestPricingPrecedence_EmptyDBKeepsBootstrapConfig", _test.TestPricingPrecedence_EmptyDBKeepsBootstrapConfig},

	{"TestResolvePricing_PrefersTenantAndEffectiveWindow", _test.TestResolvePricing_PrefersTenantAndEffectiveWindow},

	{"TestNormalizeProvider_GeminiAlias", _test.TestNormalizeProvider_GeminiAlias},

	{"TestProviderForHost_Google", _test.TestProviderForHost_Google},

	{"TestProviderForHost_VertexAISuffix", _test.TestProviderForHost_VertexAISuffix},

	{"TestProviderForHost_BedrockSuffix", _test.TestProviderForHost_BedrockSuffix},

	{"TestSupportedProviders_IncludesGoogle", _test.TestSupportedProviders_IncludesGoogle},

	{"TestGeminiParser_ParseRequest_FromPath", _test.TestGeminiParser_ParseRequest_FromPath},

	{"TestGeminiParser_ParseStreamingRequest", _test.TestGeminiParser_ParseStreamingRequest},

	{"TestGeminiParser_ParseUsage", _test.TestGeminiParser_ParseUsage},

	{"TestProviderRouteHint", _test.TestProviderRouteHint},

	{"TestVertexAIParser_ParseRequest_FromPath", _test.TestVertexAIParser_ParseRequest_FromPath},

	{"TestBedrockParser_ParseRequest_FromPath", _test.TestBedrockParser_ParseRequest_FromPath},

	{"TestOpenAIParser_ParseRequest", _test.TestOpenAIParser_ParseRequest},

	{"TestOpenAIParser_ParseRequest_Streaming", _test.TestOpenAIParser_ParseRequest_Streaming},

	{"TestOpenAIParser_ParseUsage", _test.TestOpenAIParser_ParseUsage},

	{"TestOpenAIParser_ParseStreamingUsage", _test.TestOpenAIParser_ParseStreamingUsage},

	{"TestAnthropicParser_ParseRequest", _test.TestAnthropicParser_ParseRequest},

	{"TestAnthropicParser_ParseUsage", _test.TestAnthropicParser_ParseUsage},

	{"TestAnthropicParser_ParseStreamingUsage", _test.TestAnthropicParser_ParseStreamingUsage},

	{"TestExtractVirtualKey_Bearer", _test.TestExtractVirtualKey_Bearer},

	{"TestExtractVirtualKey_XAPIKey", _test.TestExtractVirtualKey_XAPIKey},

	{"TestExtractVirtualKey_Missing", _test.TestExtractVirtualKey_Missing},

	{"TestComputeProxyCost_KnownModel", _test.TestComputeProxyCost_KnownModel},

	{"TestComputeProxyCost_UnknownModel", _test.TestComputeProxyCost_UnknownModel},

	{"TestComputeProxyCost_VersionedModel", _test.TestComputeProxyCost_VersionedModel},

	{"TestComputeProxyCost_UsesConfiguredPricing", _test.TestComputeProxyCost_UsesConfiguredPricing},

	{"TestRecordSpan_UsesCanonicalModelAttributeAndCost", _test.TestRecordSpan_UsesCanonicalModelAttributeAndCost},

	{"TestRecordSpan_ClassifiesBlockedOutcome", _test.TestRecordSpan_ClassifiesBlockedOutcome},

	{"TestRecordSpan_ClassifiesErrorOutcome", _test.TestRecordSpan_ClassifiesErrorOutcome},

	{"TestRecordSpan_ClassifiesDegradedOutcomeForFallbackSuccess", _test.TestRecordSpan_ClassifiesDegradedOutcomeForFallbackSuccess},

	{"TestRecordPolicyDecision_CreatesCanonicalDecisionRecord", _test.TestRecordPolicyDecision_CreatesCanonicalDecisionRecord},

	{"TestRecordDecision_NormalizesFallbackExplanation", _test.TestRecordDecision_NormalizesFallbackExplanation},

	{"TestProxy_MissingVirtualKey", _test.TestProxy_MissingVirtualKey},

	{"TestProxy_NonVirtualKey", _test.TestProxy_NonVirtualKey},

	{"TestProxy_UnsupportedProvider", _test.TestProxy_UnsupportedProvider},

	{"TestProxy_RealKeyNeverForwarded", _test.TestProxy_RealKeyNeverForwarded},

	{"TestParserFor_Known", _test.TestParserFor_Known},

	{"TestParserFor_Unknown", _test.TestParserFor_Unknown},

	{"TestProviderRouter_ResolveIncludesFallback", _test.TestProviderRouter_ResolveIncludesFallback},

	{"TestProviderRouter_ResolveCanaryModelRollout", _test.TestProviderRouter_ResolveCanaryModelRollout},

	{"TestProviderRouter_ApplyGoogleFallbackRewritesPathAndBody", _test.TestProviderRouter_ApplyGoogleFallbackRewritesPathAndBody},

	{"TestProxyResponseCache_RoundTrip", _test.TestProxyResponseCache_RoundTrip},

	{"TestRequestRateLimiter_EnforcesScope", _test.TestRequestRateLimiter_EnforcesScope},

}

var benchmarks = []testing.InternalBenchmark{

}

var fuzzTargets = []testing.InternalFuzzTarget{

}

var examples = []testing.InternalExample{

}

func init() {

	testdeps.ModulePath = "github.com/agentfabric/api-gateway"
	testdeps.ImportPath = "github.com/agentfabric/api-gateway/internal/proxy"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	os.Exit(m.Run())

}

