
// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	"os"

	"testing"
	"testing/internal/testdeps"



	_test "github.com/govagn/api-gateway/internal/rollouts"


)

var tests = []testing.InternalTest{

	{"TestResolve_DeterministicModelAssignment", _test.TestResolve_DeterministicModelAssignment},

	{"TestResolve_PromptReleaseUsesReleaseTag", _test.TestResolve_PromptReleaseUsesReleaseTag},

	{"TestRecordOutcome_AutoPausesCanaryOnThresholdBreach", _test.TestRecordOutcome_AutoPausesCanaryOnThresholdBreach},

}

var benchmarks = []testing.InternalBenchmark{

}

var fuzzTargets = []testing.InternalFuzzTarget{

}

var examples = []testing.InternalExample{

}

func init() {

	testdeps.ModulePath = "github.com/govagn/api-gateway"
	testdeps.ImportPath = "github.com/govagn/api-gateway/internal/rollouts"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	os.Exit(m.Run())

}

