
// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	"os"

	"testing"
	"testing/internal/testdeps"



	_test "github.com/govagn/api-gateway/internal/evals"


)

var tests = []testing.InternalTest{

	{"TestListAgentScorecards_ComputesOverallAndTrend", _test.TestListAgentScorecards_ComputesOverallAndTrend},

	{"TestGetAgentScorecard_RecommendsActionsForWeakComponents", _test.TestGetAgentScorecard_RecommendsActionsForWeakComponents},

	{"TestFirstNonEmpty", _test.TestFirstNonEmpty},

	{"TestSplitCSV", _test.TestSplitCSV},

	{"TestFirstInt", _test.TestFirstInt},

	{"TestSummarizePolicyEffectiveness", _test.TestSummarizePolicyEffectiveness},

	{"TestAggregateMetrics", _test.TestAggregateMetrics},

	{"TestMetricUnionAndHelpers", _test.TestMetricUnionAndHelpers},

	{"TestDefaultScorers", _test.TestDefaultScorers},

	{"TestScoreReliability", _test.TestScoreReliability},

	{"TestScoreLatencyThresholds", _test.TestScoreLatencyThresholds},

	{"TestScoreCostEfficiency", _test.TestScoreCostEfficiency},

	{"TestScorePolicyCoverage", _test.TestScorePolicyCoverage},

	{"TestClampAndSeverityHelpers", _test.TestClampAndSeverityHelpers},

	{"TestPolicyEventsFromAudit", _test.TestPolicyEventsFromAudit},

	{"TestScoreTraceValidatesTraceID", _test.TestScoreTraceValidatesTraceID},

	{"TestScoreTraceBuildsAndPersistsEvalRun", _test.TestScoreTraceBuildsAndPersistsEvalRun},

	{"TestScoreTraceReturnsNoRowsForEmptyTrace", _test.TestScoreTraceReturnsNoRowsForEmptyTrace},

	{"TestListRunsDelegatesToStore", _test.TestListRunsDelegatesToStore},

	{"TestCompareReleaseBuildsRegressionReport", _test.TestCompareReleaseBuildsRegressionReport},

}

var benchmarks = []testing.InternalBenchmark{

}

var fuzzTargets = []testing.InternalFuzzTarget{

}

var examples = []testing.InternalExample{

}

func init() {

	testdeps.ModulePath = "github.com/govagn/api-gateway"
	testdeps.ImportPath = "github.com/govagn/api-gateway/internal/evals"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	os.Exit(m.Run())

}

