
// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	"os"

	"testing"
	"testing/internal/testdeps"



	_test "github.com/agentfabric/api-gateway/internal/ws"


)

var tests = []testing.InternalTest{

	{"TestBuildAllowedWSOrigins_DevIncludesLocalhostDefaults", _test.TestBuildAllowedWSOrigins_DevIncludesLocalhostDefaults},

	{"TestBuildAllowedWSOrigins_StrictRequiresExplicitOrigins", _test.TestBuildAllowedWSOrigins_StrictRequiresExplicitOrigins},

	{"TestIsAllowedWSOrigin_StrictRejectsMissingOrigin", _test.TestIsAllowedWSOrigin_StrictRejectsMissingOrigin},

	{"TestIsAllowedWSOrigin_DevAllowsMissingOrigin", _test.TestIsAllowedWSOrigin_DevAllowsMissingOrigin},

	{"TestIsAllowedWSOrigin_ExplicitOriginAllowed", _test.TestIsAllowedWSOrigin_ExplicitOriginAllowed},

}

var benchmarks = []testing.InternalBenchmark{

}

var fuzzTargets = []testing.InternalFuzzTarget{

}

var examples = []testing.InternalExample{

}

func init() {

	testdeps.ModulePath = "github.com/agentfabric/api-gateway"
	testdeps.ImportPath = "github.com/agentfabric/api-gateway/internal/ws"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	os.Exit(m.Run())

}

