
// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	"os"

	"testing"
	"testing/internal/testdeps"



	_test "github.com/agentfabric/api-gateway/internal/auth"


)

var tests = []testing.InternalTest{

	{"TestGeneratePKCE_ReturnsNonEmpty", _test.TestGeneratePKCE_ReturnsNonEmpty},

	{"TestGeneratePKCE_VerifierAndChallengeAreDifferent", _test.TestGeneratePKCE_VerifierAndChallengeAreDifferent},

	{"TestGeneratePKCE_ChallengeIsS256OfVerifier", _test.TestGeneratePKCE_ChallengeIsS256OfVerifier},

	{"TestGeneratePKCE_UniqueEachCall", _test.TestGeneratePKCE_UniqueEachCall},

	{"TestGeneratePKCE_VerifierIsURLSafe", _test.TestGeneratePKCE_VerifierIsURLSafe},

	{"TestGenerateNonce_ReturnsNonEmpty", _test.TestGenerateNonce_ReturnsNonEmpty},

	{"TestGenerateNonce_UniqueEachCall", _test.TestGenerateNonce_UniqueEachCall},

	{"TestValidateConfig_StrictRejectsPartialOIDCConfiguration", _test.TestValidateConfig_StrictRejectsPartialOIDCConfiguration},

	{"TestValidateConfig_StrictRejectsMissingRedirectWhenSSORequired", _test.TestValidateConfig_StrictRejectsMissingRedirectWhenSSORequired},

	{"TestValidateConfig_StrictAcceptsCompleteOptionalOIDCConfig", _test.TestValidateConfig_StrictAcceptsCompleteOptionalOIDCConfig},

	{"TestParseIDToken_ValidToken", _test.TestParseIDToken_ValidToken},

	{"TestParseIDToken_ExpiredToken", _test.TestParseIDToken_ExpiredToken},

	{"TestParseIDToken_MissingSubject", _test.TestParseIDToken_MissingSubject},

	{"TestParseIDToken_InvalidFormat_TwoPartToken", _test.TestParseIDToken_InvalidFormat_TwoPartToken},

	{"TestParseIDToken_InvalidFormat_EmptyString", _test.TestParseIDToken_InvalidFormat_EmptyString},

	{"TestIssueAFToken_ValidClaims", _test.TestIssueAFToken_ValidClaims},

	{"TestIssueAFToken_ExpiresWithinSessionMaxAge", _test.TestIssueAFToken_ExpiresWithinSessionMaxAge},

	{"TestIssueAFToken_IssuerIsAgentFabric", _test.TestIssueAFToken_IssuerIsAgentFabric},

	{"TestIssueAFToken_AudienceIsPortal", _test.TestIssueAFToken_AudienceIsPortal},

	{"TestStateCookieRoundTrip", _test.TestStateCookieRoundTrip},

	{"TestStateCookieVerify_TamperedCookie", _test.TestStateCookieVerify_TamperedCookie},

	{"TestStateCookieVerify_InvalidJWT", _test.TestStateCookieVerify_InvalidJWT},

	{"TestStateCookieVerify_WrongSecret", _test.TestStateCookieVerify_WrongSecret},

	{"TestIsHTTPS_ForwardedProtoHeader", _test.TestIsHTTPS_ForwardedProtoHeader},

	{"TestIsHTTPS_ForwardedProtoCommaSeparated", _test.TestIsHTTPS_ForwardedProtoCommaSeparated},

	{"TestIsHTTPS_PlainHTTP", _test.TestIsHTTPS_PlainHTTP},

	{"TestBearerToken_ExtractsBearerPrefix", _test.TestBearerToken_ExtractsBearerPrefix},

	{"TestBearerToken_CaseInsensitive", _test.TestBearerToken_CaseInsensitive},

	{"TestBearerToken_EmptyWhenNoBearerPrefix", _test.TestBearerToken_EmptyWhenNoBearerPrefix},

	{"TestBearerToken_EmptyWhenNoHeader", _test.TestBearerToken_EmptyWhenNoHeader},

	{"TestNewOIDCHandler_DefaultScopes", _test.TestNewOIDCHandler_DefaultScopes},

	{"TestNewOIDCHandler_DefaultSessionMaxAge", _test.TestNewOIDCHandler_DefaultSessionMaxAge},

	{"TestNewOIDCHTTPClient_TimeoutConfigured", _test.TestNewOIDCHTTPClient_TimeoutConfigured},

	{"TestPasswordLogin_ValidCredentials_Returns200", _test.TestPasswordLogin_ValidCredentials_Returns200},

	{"TestPasswordLogin_ValidCredentials_ReturnsToken", _test.TestPasswordLogin_ValidCredentials_ReturnsToken},

	{"TestPasswordLogin_TokenIsValidJWT", _test.TestPasswordLogin_TokenIsValidJWT},

	{"TestPasswordLogin_WrongPassword_Returns401", _test.TestPasswordLogin_WrongPassword_Returns401},

	{"TestPasswordLogin_WrongUsername_Returns401", _test.TestPasswordLogin_WrongUsername_Returns401},

	{"TestPasswordLogin_EmptyUsername_Returns400", _test.TestPasswordLogin_EmptyUsername_Returns400},

	{"TestPasswordLogin_EmptyPassword_Returns400", _test.TestPasswordLogin_EmptyPassword_Returns400},

	{"TestPasswordLogin_InvalidJSON_Returns400", _test.TestPasswordLogin_InvalidJSON_Returns400},

	{"TestPasswordLogin_CustomCredentials_ValidLogin", _test.TestPasswordLogin_CustomCredentials_ValidLogin},

	{"TestPasswordLogin_DefaultCredentialsFallback", _test.TestPasswordLogin_DefaultCredentialsFallback},

	{"TestPasswordLogin_WhitespaceTrimmingUsername", _test.TestPasswordLogin_WhitespaceTrimmingUsername},

	{"TestRefresh_ValidToken_Returns200", _test.TestRefresh_ValidToken_Returns200},

	{"TestRefresh_ValidToken_ReturnsNewToken", _test.TestRefresh_ValidToken_ReturnsNewToken},

	{"TestRefresh_NewTokenHasFreshExpiry", _test.TestRefresh_NewTokenHasFreshExpiry},

	{"TestRefresh_NewTokenPreservesIdentity", _test.TestRefresh_NewTokenPreservesIdentity},

	{"TestCallback_MissingStateQuery_Returns400", _test.TestCallback_MissingStateQuery_Returns400},

	{"TestCallback_StateMismatch_Returns401", _test.TestCallback_StateMismatch_Returns401},

	{"TestRefresh_NoToken_Returns401", _test.TestRefresh_NoToken_Returns401},

	{"TestRefresh_InvalidToken_Returns401", _test.TestRefresh_InvalidToken_Returns401},

	{"TestRefresh_WrongSecret_Returns401", _test.TestRefresh_WrongSecret_Returns401},

	{"TestRefresh_ExpiresInMatchesSessionMaxAge", _test.TestRefresh_ExpiresInMatchesSessionMaxAge},

}

var benchmarks = []testing.InternalBenchmark{

}

var fuzzTargets = []testing.InternalFuzzTarget{

}

var examples = []testing.InternalExample{

}

func init() {

	testdeps.ModulePath = "github.com/agentfabric/api-gateway"
	testdeps.ImportPath = "github.com/agentfabric/api-gateway/internal/auth"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	os.Exit(m.Run())

}

