
// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	"os"

	"testing"
	"testing/internal/testdeps"



	_test "github.com/agentfabric/collector/internal/auth"


)

var tests = []testing.InternalTest{

	{"TestValidateToken_Valid", _test.TestValidateToken_Valid},

	{"TestValidateToken_WrongSecret", _test.TestValidateToken_WrongSecret},

	{"TestValidateToken_Expired", _test.TestValidateToken_Expired},

	{"TestValidateToken_Malformed", _test.TestValidateToken_Malformed},

	{"TestValidateToken_EmptySecret_AllowsAll", _test.TestValidateToken_EmptySecret_AllowsAll},

	{"TestValidateHTTP_ValidBearerHeader", _test.TestValidateHTTP_ValidBearerHeader},

	{"TestValidateHTTP_MissingHeader", _test.TestValidateHTTP_MissingHeader},

	{"TestValidateHTTP_MalformedHeader", _test.TestValidateHTTP_MalformedHeader},

	{"TestValidateHTTP_BearerCaseInsensitive", _test.TestValidateHTTP_BearerCaseInsensitive},

	{"TestValidateHTTP_EmptyBearerTokenRejected", _test.TestValidateHTTP_EmptyBearerTokenRejected},

	{"TestGRPCTokenValidator_BearerCaseInsensitive", _test.TestGRPCTokenValidator_BearerCaseInsensitive},

	{"TestTokenBucket_AllowsUnderLimit", _test.TestTokenBucket_AllowsUnderLimit},

	{"TestTokenBucket_RejectsOverBurst", _test.TestTokenBucket_RejectsOverBurst},

	{"TestTokenBucket_RefillsOverTime", _test.TestTokenBucket_RefillsOverTime},

}

var benchmarks = []testing.InternalBenchmark{

}

var fuzzTargets = []testing.InternalFuzzTarget{

}

var examples = []testing.InternalExample{

}

func init() {

	testdeps.ModulePath = "github.com/agentfabric/collector"
	testdeps.ImportPath = "github.com/agentfabric/collector/internal/auth"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	os.Exit(m.Run())

}

