
// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	"os"

	"testing"
	"testing/internal/testdeps"



	_test "github.com/govagn/api-gateway/internal/memory"


)

var tests = []testing.InternalTest{

	{"TestRecordChange_NormalizesFields", _test.TestRecordChange_NormalizesFields},

	{"TestCreateEvidenceBundle_AssemblesReleaseIncidentEvidence", _test.TestCreateEvidenceBundle_AssemblesReleaseIncidentEvidence},

	{"TestCreateEvidenceBundle_UsesExplicitRecommendationSelection", _test.TestCreateEvidenceBundle_UsesExplicitRecommendationSelection},

}

var benchmarks = []testing.InternalBenchmark{

}

var fuzzTargets = []testing.InternalFuzzTarget{

}

var examples = []testing.InternalExample{

}

func init() {

	testdeps.ModulePath = "github.com/govagn/api-gateway"
	testdeps.ImportPath = "github.com/govagn/api-gateway/internal/memory"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	os.Exit(m.Run())

}

