
// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	"os"

	"testing"
	"testing/internal/testdeps"



	_test "github.com/agentfabric/api-gateway/internal/vault"


)

var tests = []testing.InternalTest{

	{"TestNew_ValidKey", _test.TestNew_ValidKey},

	{"TestNew_TooShort", _test.TestNew_TooShort},

	{"TestNew_NotHex", _test.TestNew_NotHex},

	{"TestEncryptDecrypt_RoundTrip", _test.TestEncryptDecrypt_RoundTrip},

	{"TestEncryptDecrypt_DifferentNonceEachTime", _test.TestEncryptDecrypt_DifferentNonceEachTime},

	{"TestDecrypt_TamperedCiphertext", _test.TestDecrypt_TamperedCiphertext},

	{"TestDecrypt_TooShort", _test.TestDecrypt_TooShort},

	{"TestGenerateVirtualKey_Format", _test.TestGenerateVirtualKey_Format},

	{"TestGenerateVirtualKey_Unique", _test.TestGenerateVirtualKey_Unique},

	{"TestDecrypt_WrongMasterKey", _test.TestDecrypt_WrongMasterKey},

}

var benchmarks = []testing.InternalBenchmark{

}

var fuzzTargets = []testing.InternalFuzzTarget{

}

var examples = []testing.InternalExample{

}

func init() {

	testdeps.ModulePath = "github.com/agentfabric/api-gateway"
	testdeps.ImportPath = "github.com/agentfabric/api-gateway/internal/vault"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	os.Exit(m.Run())

}

