
// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	"os"

	"testing"
	"testing/internal/testdeps"



	_test "github.com/govagn/api-gateway/internal/policy"


)

var tests = []testing.InternalTest{

	{"TestEvaluateTraffic_PrefersTenantSpecificMatch", _test.TestEvaluateTraffic_PrefersTenantSpecificMatch},

	{"TestEvaluateTraffic_HonorsTokenCeiling", _test.TestEvaluateTraffic_HonorsTokenCeiling},

	{"TestEvaluateDLP_RedactsDetectedSecrets", _test.TestEvaluateDLP_RedactsDetectedSecrets},

	{"TestEvaluateDLP_RespectsScope", _test.TestEvaluateDLP_RespectsScope},

	{"TestEvaluateTraffic_RegoDecisionMode", _test.TestEvaluateTraffic_RegoDecisionMode},

	{"TestEvaluateTraffic_RuleConditions", _test.TestEvaluateTraffic_RuleConditions},

	{"TestEvaluateDLP_GuardrailsPromptInjection", _test.TestEvaluateDLP_GuardrailsPromptInjection},

	{"TestEvaluateDLP_GuardrailsSchema", _test.TestEvaluateDLP_GuardrailsSchema},

	{"TestSimulatePolicySet", _test.TestSimulatePolicySet},

}

var benchmarks = []testing.InternalBenchmark{

}

var fuzzTargets = []testing.InternalFuzzTarget{

}

var examples = []testing.InternalExample{

}

func init() {

	testdeps.ModulePath = "github.com/govagn/api-gateway"
	testdeps.ImportPath = "github.com/govagn/api-gateway/internal/policy"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	os.Exit(m.Run())

}

