
// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	"os"

	"testing"
	"testing/internal/testdeps"



	_test "github.com/govagn/collector/internal/receiver"


)

var tests = []testing.InternalTest{

	{"TestExport_NilRequest_ReturnsEmpty", _test.TestExport_NilRequest_ReturnsEmpty},

	{"TestExport_EmptyResourceSpans_ReturnsEmpty", _test.TestExport_EmptyResourceSpans_ReturnsEmpty},

	{"TestExport_ValidSpan_Accepted", _test.TestExport_ValidSpan_Accepted},

	{"TestExport_BatchTooLarge_ReturnsResourceExhausted", _test.TestExport_BatchTooLarge_ReturnsResourceExhausted},

	{"TestFlattenSpans_Empty", _test.TestFlattenSpans_Empty},

	{"TestFlattenSpans_MultipleScopes", _test.TestFlattenSpans_MultipleScopes},

}

var benchmarks = []testing.InternalBenchmark{

}

var fuzzTargets = []testing.InternalFuzzTarget{

}

var examples = []testing.InternalExample{

}

func init() {

	testdeps.ModulePath = "github.com/govagn/collector"
	testdeps.ImportPath = "github.com/govagn/collector/internal/receiver"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	os.Exit(m.Run())

}

