import { Plug, Link2, Rocket, RefreshCw, Copy } from 'lucide-react'
import { useMemo, useState } from 'react'
import { useConnectivityStatus, useProbeConnectivity } from '../hooks/api'

function statusColor(status: string) {
  switch (status) {
    case 'connected':
      return '#10B981'
    case 'probed':
      return '#60A5FA'
    case 'stale':
      return '#F59E0B'
    default:
      return '#EF4444'
  }
}

function formatLastSeen(value?: string) {
  if (!value) return 'Never'
  return new Date(value).toLocaleString()
}

export default function ConnectivityPage() {
  const { data, isLoading, refetch, isFetching } = useConnectivityStatus()
  const probe = useProbeConnectivity()
  const [copyState, setCopyState] = useState<string>('')

  const startupCommands = useMemo(() => data?.startup_installer ?? {}, [data])

  const handleProbe = async (adapter: string) => {
    await probe.mutateAsync(adapter)
    await refetch()
  }

  const copyText = async (value: string, key: string) => {
    await navigator.clipboard.writeText(value)
    setCopyState(key)
    window.setTimeout(() => setCopyState(''), 1200)
  }

  return (
    <div style={{ padding: '20px 0' }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 20 }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
          <Plug size={28} style={{ color: '#0A84FF' }} />
          <h1 style={{ margin: 0, fontSize: 26, fontWeight: 700 }}>Connectivity</h1>
        </div>
        <button
          onClick={() => refetch()}
          disabled={isFetching}
          style={{
            border: '1px solid var(--layer-border)',
            background: 'var(--layer)',
            color: 'var(--text-primary)',
            borderRadius: 8,
            padding: '8px 12px',
            cursor: 'pointer',
            display: 'flex',
            alignItems: 'center',
            gap: 6,
          }}
        >
          <RefreshCw size={14} />
          Refresh
        </button>
      </div>

      <div style={{ fontSize: 13, color: 'var(--text-secondary)', marginBottom: 20 }}>
        Live signal status for Codex, Claude Code, Antigravity, and VSCode. Use <b>Probe</b> to validate ingestion wiring end-to-end.
      </div>
      <div style={{ fontSize: 12, color: '#93C5FD', marginBottom: 14 }}>
        `PROBED` means synthetic validation traffic was generated by Govagn, not a real external agent session.
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(260px, 1fr))', gap: 12, marginBottom: 24 }}>
        {(data?.adapters ?? []).map((adapter) => (
          <div key={adapter.id} style={{ border: '1px solid var(--layer-border)', borderRadius: 10, background: 'var(--layer)', padding: 14 }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 10 }}>
              <div style={{ fontSize: 15, fontWeight: 700 }}>{adapter.name}</div>
              <div style={{ fontSize: 12, fontWeight: 700, color: statusColor(adapter.status), textTransform: 'uppercase' }}>{adapter.status}</div>
            </div>
            <div style={{ fontSize: 12, color: 'var(--text-secondary)', marginBottom: 6 }}>Last seen: {formatLastSeen(adapter.last_seen)}</div>
            <div style={{ fontSize: 12, color: 'var(--text-secondary)', marginBottom: 6 }}>Framework: {adapter.framework || 'unknown'}</div>
            <div style={{ fontSize: 11, color: 'var(--text-tertiary)', marginBottom: 6 }}>
              Signal source: {adapter.signal_source || 'none'}
            </div>
            <div style={{ fontSize: 11, color: 'var(--text-tertiary)', marginBottom: 8 }}>
              {adapter.connection_guidance || 'No guidance available'}
            </div>
            {adapter.detected_trace_id && (
              <div style={{ fontSize: 11, color: '#60A5FA', marginBottom: 8 }}>
                Trace: {adapter.detected_trace_id.slice(0, 12)}...
              </div>
            )}
            <button
              onClick={() => handleProbe(adapter.id)}
              disabled={probe.isPending}
              style={{
                width: '100%',
                border: 'none',
                borderRadius: 6,
                padding: '8px 10px',
                background: '#0A84FF20',
                color: '#60A5FA',
                fontWeight: 600,
                cursor: 'pointer',
              }}
            >
              {probe.isPending ? 'Probing...' : `Probe ${adapter.name}`}
            </button>
          </div>
        ))}
      </div>

      <div style={{ border: '1px solid var(--layer-border)', borderRadius: 10, background: 'var(--layer)', padding: 16, marginBottom: 16 }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 10 }}>
          <Rocket size={16} style={{ color: '#BF5AF2' }} />
          <h2 style={{ margin: 0, fontSize: 16 }}>Customer Installable Profiles</h2>
        </div>
        <div style={{ fontSize: 12, color: 'var(--text-secondary)', marginBottom: 12 }}>
          Apply these env profiles to route traffic and telemetry through Govagn every run.
        </div>
        {(data?.install_profiles ?? []).map((profile) => (
          <div key={profile.id} style={{ border: '1px solid var(--layer-border)', borderRadius: 8, padding: 12, marginBottom: 10 }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 6 }}>
              <Link2 size={14} style={{ color: '#FFD60A' }} />
              <div style={{ fontSize: 14, fontWeight: 700 }}>{profile.name}</div>
            </div>
            <div style={{ fontSize: 12, color: 'var(--text-secondary)', marginBottom: 8 }}>{profile.description}</div>
            <div style={{ fontFamily: 'monospace', fontSize: 11, color: '#93C5FD', whiteSpace: 'pre-wrap' }}>
              {Object.entries(profile.env).map(([k, v]) => `${k}=${v}`).join('\n')}
            </div>
          </div>
        ))}
      </div>

      <div style={{ border: '1px solid var(--layer-border)', borderRadius: 10, background: 'var(--layer)', padding: 16 }}>
        <div style={{ fontSize: 16, fontWeight: 700, marginBottom: 10 }}>Auto-start on Machine Boot</div>
        <div style={{ fontSize: 12, color: 'var(--text-secondary)', marginBottom: 10 }}>
          Install startup automation once, then Govagn launches automatically after reboot.
        </div>
        {Object.entries(startupCommands).map(([os, cmd]) => (
          <div key={os} style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 8 }}>
            <div style={{ minWidth: 70, fontSize: 12, textTransform: 'uppercase', color: 'var(--text-secondary)' }}>{os}</div>
            <code style={{ flex: 1, background: '#0B1220', padding: '6px 8px', borderRadius: 6, fontSize: 11, color: '#C4B5FD' }}>{cmd}</code>
            <button
              onClick={() => copyText(cmd, os)}
              style={{
                border: '1px solid var(--layer-border)',
                background: 'transparent',
                color: copyState === os ? '#10B981' : 'var(--text-secondary)',
                borderRadius: 6,
                padding: '6px 8px',
                cursor: 'pointer',
                display: 'flex',
                alignItems: 'center',
                gap: 4,
              }}
            >
              <Copy size={12} />
              {copyState === os ? 'Copied' : 'Copy'}
            </button>
          </div>
        ))}
      </div>

      {isLoading && (
        <div style={{ marginTop: 12, fontSize: 12, color: 'var(--text-secondary)' }}>
          Loading connectivity status...
        </div>
      )}
    </div>
  )
}
